### ISSUE TITLE
[BUG] Dark Souls  Remastered doesn't launch

### ISSUE THREAD

**Issue by sidaodomorro** [longjunyu2/winlator#10]
**Device Information**
- Device Model: [Xiaomi POCO F5]
- Device Processor Model: [SD 7+ GEN 2]
- Android Version: [14]
- Kernel Version: [5.10.214-gki-g9ceeb73e3362]

**Application Configuration Information**
- App Version: [7.1.1]
- Display Driver: [Turnip-24.1.0]
- dxwrapper: [DXVK-2.3.1]
- box64 Version: [0.3.0]
- box64 Preset: [Compatibility]

**Description of the Issue**
Dark souls does not launch in any circumstances, i tried every preset possible, and it still did not launch.

**Steps to Reproduce**
1. Create Container following my configuration
2. Open container 
3. Click on darksoulsremastered.exe

**Expected Behavior**
I expected Dark Souls to launch properly 

**Additional Information**
Dark souls remastered opens in winlator 7.1 original, but not on this one.

**Comment by longjunyu2** [comment]
Hello @sidaodomorro , I updated box64, which may fixed this bug.

**Comment by sidaodomorro** [comment]
Yes! Now it launches !!
