### ISSUE TITLE
[BUG] 8GEN2 can't boot game on Wine 9.16/9.15. Only Wine 9.2 can run games.

### ISSUE THREAD

**Issue by Coldboy195** [longjunyu2/winlator#101]
**Device Information**
- Device Model: Xiaomi 13
- Device Processor Model: 8Gen2
- Android Version: 14
- Kernel Version: 5.15.123

**Application Configuration Information**
- App Version: 7.1.3
- Display Driver: Turnip-24.1.0/24.3.0
- dxwrapper: Any Dxvk
- box64 Version: 0.3.0/0.3.1
- box64 Preset: Compatibility/Any configs

**Description of the Issue**
Wine 9.15 and 9.16 can't boot games (Black Screen), only Wine 9.2 can run games.
Tested on 8Gen1 (samsung Android 14) All Wines work fine.
So this is bug on 8Gen2?

**Comment by longjunyu2** [comment]
What game?

**Comment by Coldboy195** [comment]
> What game?

Wine 9.15/ 9.16 can't run any games.
Just Wine 9.2 can run.

Back to 7.1.2 works fine. So i think 7.1.3 not for 8Gen2.
I hope 7.1.4 will fix this bug.

**Comment by longjunyu2** [comment]
no :(

**Comment by Coldboy195** [comment]
> no :(

NVM, I Fixed it.
Now 7.1.3 works perfect.
Thank you so much.
