### ISSUE TITLE
[Performance Analysis] WinlatorGlibC development build impressions - Test #2

### ISSUE THREAD

**Issue by ghost** [longjunyu2/winlator#106]
Device Information

Device Model: [RedMagic 9 Pro]
Device Processor Model: [SnapDragon 8 gen 3]
Android Version: [14]
Kernel Version: [6.1.25]

Application Configuration Information

App Version: [7.1.3]
Display Driver: [Turnip-24.3.0 Pipetto crypto]
dxwrapper: [DXVK Esync/Gplaysync]
box64 Version: [0.3.0]
box64 Preset: [Preset Custom]
___
I take inspiration from the previous test in WoW64 environment and version 9.16 that you can consult at the following link: https://github.com/longjunyu2/winlator/issues/86

In this new test I made some changes to the Box64 variables, in order to obtain a result (in stable fps) more or less similar to the 960x544 resolution of the previous test.

The resolution adopted is in fact 1280x720p for this last test.

Demonstration video below: [WineGlibC 9.16 Test #2](https://gofile.io/d/MKS0Ie)

I remind all those who want to run the same test and with the same game (and play with environment variables), to enable the items: Occlusion (SSAO, volumetric light simulation), TressFX (physics of hair, grass and other objects in the scenario) and Tessellation (morphology and modeling of textures and terrain)

---
A personal thought, that I would like to share with those who, like me, want to retro-gaming in general and tend to follow (and/or trust and participate) with interest in this innovative project (WineGlibC).

I have noticed that in the various problems, very often there is a tendency to not follow the developer's advice (it happens in this repository, as well as in other repositories and other projects), but instead there is a tendency to follow one's own "philosophy" (as if the suggestions given were nothing more than a sort of "offense").

Opening a generic issue, where a generic problem is described (like: Hey! I ran the exe x,y,z, but it doesn't work!), will NEVER lead to a solution that satisfies that specific problem. (in addition to wasting precious time for the developer or developers of a project)

Simply because the developer or developers of a project (but also users who would like to help) do not have a "crystal ball" to get into people's heads (and understand what kind of error it is, if it is the game itself, the version of Wine in use, the version of drivers in use, the version of Box in use, the lack of libraries and/or plugins specific to the type of game, etc.)

Therefore, the best advice is always to enable log-debug from the settings of the WineGlibC application and then proceed to attach them in the discussion of the problem.

[Optional] <<for the more "Nerd", or for those who also use the Android distribution trace-log (in the case of exotic and/or custom ROMs), there are items that can be set through Developer Options (Kernel trace log, Memory, HW, Etc.)>>

Thanks.

**Comment by lvonasek** [comment]
Nice. Thank you for supporting this project.

Note that the errors in logs are usually readable for non-developers. E.g. "xxx.DLL not found" is a problem where you can find a missing on the internet and after putting it into the right folder it simply starts working.

We developers usually prioritize well reported bugs with enough "hints" about what could possibly go wrong.
