### ISSUE TITLE
GOG installers fail

### ISSUE THREAD

**Issue by QrTa** [longjunyu2/winlator#11]
Device Model: POCO F3
- Device Processor Model: Snapdragon 870
- Android Version: 14
- Kernel version ![Screenshot_2024-08-08-07-47-36-030_com.android.settings-edit.jpg](https://github.com/user-attachments/assets/e546c9b5-2b62-49c5-9aa1-5c5be4b139d2)

Not matter what settings are used. Same happening just with different speed (performance vs compatibility) but the result is the same

![Screenshot_2024-08-07-20-39-05-661_ru.zdevs.zarchiver.jpg](https://github.com/user-attachments/assets/a641d65e-5b27-45bd-b02c-f869885f2d7b)
The installer looks running in the background still uses space but the installer just shows this and never finish it.

Tried to install It using vanilla Winlator and it's installed, but the game still not starting, crashing on startup. 
I this case it was Crysis installer but GOG installers are the same. 

I tried to install PowerISO but that's can't even start the installer.

**Comment by QrTa** [comment]
How can I provide you more info about the crash of the game?
 Or to other games? 

Is there a log file which is created after game crashes? Or even Winlator crashes?

**Comment by QrTa** [comment]
Thanks! Then I will add that log afternoon.

**Comment by Darkwulfer** [comment]
Mine worked fine, i used to install witcher 1 EE from my gog account and it completed within 15 minutes.

**Comment by longjunyu2** [comment]
Maybe fixed in v7.1.2. I recompiled box64, and this will fix some issues for 870.
