### ISSUE TITLE
Could you please add this ~ in the keyboard binding sect. 

### ISSUE THREAD

**Issue by LeoHvnTeR** [longjunyu2/winlator#113]
This button

![IMG_20240914_220730](https://github.com/user-attachments/assets/a3ffdc56-3b92-4763-aa97-540ca71c8434)

**Comment by lvonasek** [comment]
The key binding added. It will be in 7.1.4 once it is released.

Note that default character for that button is ` (I remember Doom/Quake games use that to open the console).
To write ~ with that button you need to hold shift.
