### ISSUE TITLE
Install Specific Wine versions?

### ISSUE THREAD

**Issue by dave9292** [longjunyu2/winlator#131]
Hi!  Is it possible to install WINE 8.14 GE Custom via the Contents tab? I have no idea how to do this, but I really need it for Sims 2

**Comment by longjunyu2** [comment]
@dave9292
Sorry, I don't think it will work. The experimental WoW64 support in Wine versions below 9.0 is very poor, and Winlator relies on it to run 32-bit programs. In my previous tests, Wine 8.x couldn't even open testd3d.exe properly.
Could you describe the issues you encountered while trying to run The Sims 2? Maybe someone here can help you.

**Comment by Coldboy195** [comment]
> @dave9292 Sorry, I don't think it will work. The experimental WoW64 support in Wine versions below 9.0 is very poor, and Winlator-Glibc relies on it to run 32-bit programs. In my previous tests, Wine 8.x couldn't even open testd3d.exe properly. Could you describe the issues you encountered while trying to run The Sims 2? Maybe someone here can help you.

Hi bro.
Can we install 9.0 proton?
And where is dxvk.conf? I can't find it. I need it to try fix game playable.
Thank you, i just like your build, dont like mods version.

**Comment by longjunyu2** [comment]
@Coldboy195
Proton 9.0 is currently not working on Winlator, leading to a black screen. I suspect the issue might stem from the X server implementation. I'm working on replacing X with Wayland for Winlator, and this problem may be resolved in the future.
The `dxvk.conf` file can be found at `/data/data/com.winlator/files/imagefs/home/xuser/.config/dxvk.conf`, or you can navigate to Winlator’s private folder via a file manager and find it under `files/imagefs/home/xuser/.config/dxvk.conf`. You can also use the `DXVK_CONFIG_FILE` environment variable to specify the location of the `dxvk.conf` file.

**Comment by Coldboy195** [comment]
> @Coldboy195 Proton 9.0 is currently not working on Winlator, leading to a black screen. I suspect the issue might stem from the X server implementation. I'm working on replacing X with Wayland for Winlator, and this problem may be resolved in the future. The `dxvk.conf` file can be found at `/data/data/com.winlator/files/imagefs/home/xuser/.config/dxvk.conf`, or you can navigate to Winlator’s private folder via a file manager and find it under `files/imagefs/home/xuser/.config/dxvk.conf`. You can also use the `DXVK_CONFIG_FILE` environment variable to specify the location of the `dxvk.conf` file.

Thank bro. 
Im waiting your new build wayland, maybe better.

**Comment by longjunyu2** [comment]
@Coldboy195 create it mantually, winlator won't create dxvk.conf because of #3 .

**Comment by dave9292** [comment]
> @dave9292 Sorry, I don't think it will work. The experimental WoW64 support in Wine versions below 9.0 is very poor, and Winlator-Glibc relies on it to run 32-bit programs. In my previous tests, Wine 8.x couldn't even open testd3d.exe properly. Could you describe the issues you encountered while trying to run The Sims 2? Maybe someone here can help you.

Thanks for the reply! sorry to hear that, will have to continue playing Sims 2 on mobox, but it stopped updating, and there shitty controls only available via termux11 "mouse helper" and I really like Winlator overall. Thanks again for your work, i (we) appreciate it!
