### ISSUE TITLE
Fix Shaking Games

### ISSUE THREAD

**Issue by TheBoxGame** [longjunyu2/winlator#132]
Hello, I have a question. Will the next version fix the problem with the shaking image in games because when I used voodoo 2 3dfx the problem disappeared and when I use WineD3D DXVK? Or the image is black, the sound is there but the image is black

https://github.com/user-attachments/assets/d45905d2-9d0d-4eeb-83d1-24f1ca8fe023

**Comment by TheBoxGame** [comment]
@ajay9634 how to download

**Comment by lvonasek** [comment]
According to https://github.com/longjunyu2/winlator/issues/61#issuecomment-2322891009 it's not possible with the supported Wine versions.

I am not able to fix it. Use Ajay's version to play these games:
https://github.com/ajay9634/winlator-ajay-prefix/releases

**Comment by TheBoxGame** [comment]
> > Zgodnie z [#61 (komentarz)](https://github.com/longjunyu2/winlator/issues/61#issuecomment-2322891009) nie jest to możliwe w przypadku stosowania wersji Wine.
> > Nie jestem w stanie tego przechowywania. użyj wersji Ajay'a, aby zagrać w tej grze: 
> > https://github.com/ajay9634/winlator-ajay-prefix/releases
> 
> Przekonaj się, że jest gotowe repozytorium z poradnikiem, ale link Mega taki jest sam.
> 
> Wypuściłem nową wersję 10.12 z moboxem, kompatybilną z Dark OS.
> 
> https://github.com/ajay9634/Ajay-prefix

and what next
