### ISSUE TITLE
flash game doesnt open

### ISSUE THREAD

**Issue by gg676** [longjunyu2/winlator#134]
i wanna play a flash game but for some reason it doesn't open at all when i try to open it shows a black screen and then closes the app i dont know why this happening but can someone tell me

**Comment by pppaa08** [comment]
why not using ruffle?

**Comment by gg676** [comment]
no bro i downloaded a file of the game and i try to open but it wont

**Comment by pppaa08** [comment]
> no bro i downloaded a file of the game and i try to open but it wont

what kind of file? End with .exe or .swf?

**Comment by gg676** [comment]
exe

**Comment by gg676** [comment]
i figured it out anyways

**Comment by gg676** [comment]
i fixed it
