### ISSUE TITLE
Why can VirGL only support DX9?

### ISSUE THREAD

**Issue by pppaa08** [longjunyu2/winlator#139]
I learned that VirGL can expose up to OpenGL 4.x API on GLES-only devices, but why is the DX capability limited to DX9?
![Screenshot_20240930_113616_com winlator_edit_25907497240838](https://github.com/user-attachments/assets/9f96252d-2ff8-4f32-83c0-74e8336fa059)

**Comment by MarkZingrim** [comment]
No it can go upto dx10 in opengl 3.3
