### ISSUE TITLE
[BUG] instalador de Ori and the will of the wisps se cierra al empezar instalación del juego.

### ISSUE THREAD

**Issue by FullDany** [longjunyu2/winlator#14]
**Device Information**
- Device Model: [e.g., Samsung Galaxy S20 ultra]
- Device Processor Model: [snapdragon 865]
- Android Version: [e.g., 13]
- Kernel Version: [e.g., 4.19.112]

**Application Configuration Information**
- App Version: [e.g., 7.1.1]
- Display Driver: [e.g., Turnip-24.1.0]
- dxwrapper: [e.g., DXVK-2.3.1]
- box64 Version: [e.g., 0.3.0]
- box64 Preset: [e.g., Compatibility]

**Description of the Issue**
Please provide a clear and concise description of the problem. For example, "The app crashes when I try to open the settings menu."

**Steps to Reproduce**
Please describe the steps to reproduce the issue:
1. Al abrir el setup el instalador tiene un lenguaje chino
2. Al instalar el juego 
3. se cierra el instalador al 1% 

**Expected Behavior**
Please describe what you expected to happen. For example, "I expected to see the advanced settings without the app crashing."

**Screenshots**
If applicable, add screenshots to help explain your problem. You can attach screenshots here.

**Additional Information**
Please provide any other relevant information or context. For example, "This issue started happening after updating to version 1.2.3."

**Comment by longjunyu2** [comment]
excuse me, I don't understand, english please!
