### ISSUE TITLE
[help] arm

### ISSUE THREAD

**Issue by Dragonfire75** [longjunyu2/winlator#147]
**Device Information**
- Device Model: [Samsung Galaxy Tab 10.1 (2016) (SM-T585]
- Device Processor Model: [Exynos octa 7870]
- Android Version: [8.1.0]
- Kernel Version: [3.18.14-17282421 (T585XXU7CUH1)]
- help me not have arm64
:(

![Screenshot_20241025-113800_CPU-Z](https://github.com/user-attachments/assets/c9a47524-36a7-43e6-a8a9-368720860886)

**Comment by lvonasek** [comment]
I am sorry, we do not have the resources to support such an old device.
