### ISSUE TITLE
PLEASE ADD CUSTOM WINE SUPPORT

### ISSUE THREAD

**Issue by Saikatsaha1996** [longjunyu2/winlator#15]
This is not an issue.. just Request

can you add more wine or any options for add custom wine?
Because in wine 9.13 had issue with .Net core .. i unable to play .Net core depending games

I am closing issue.. if you can please focus on custom wine or more wine installation options

**Comment by longjunyu2** [comment]
Nice idea !

**Comment by Saikatsaha1996** [comment]
@longjunyu2 log
[logs.txt](https://github.com/user-attachments/files/16590078/logs.txt)

**Comment by Saikatsaha1996** [comment]
## Just asking.. not an issue..
## asking for improvement 
In `Termux glibc`, also had exactly same airplane texture (black).. in your `winlator-glibc` also had same Texture like this 
![Screenshot_2024-09-01-11-48-55-18_99c04817c0de5652397fc8b56c3b3817](https://github.com/user-attachments/assets/56d60cbd-1f0c-48a4-9e90-04e5d60237be)


But with `proot & winlator glibc (frost)` cubemap airplane texture okay like this.. 
![Screenshot_2024-09-01-11-40-47-35_99c04817c0de5652397fc8b56c3b3817](https://github.com/user-attachments/assets/7994a71b-c565-480a-ac21-f027bad352c3)


Is it for any dependency problem?
