### ISSUE TITLE
Is the Proprietary Vulkan driver possible in Winlator?

### ISSUE THREAD

**Issue by Crauzer58** [longjunyu2/winlator#150]
On [HangOver-Termux](https://github.com/alexvorxx/hangover-termux/releases), they can use the Proprietary Vulkan driver, is it applicable to Winlator?

**Comment by lvonasek** [comment]
There would be needed some patches on the driver itself but then it should work.

**Comment by evmlinux** [comment]
mesa-vulkan-icd-wrapper

https://github.com/xMeM/termux-packages/tree/dev/wrapper
