### ISSUE TITLE
[BUG]Winlator 7.1.3 with Native Glibc version's direct3d test doesn't work on turnip but works only on VirGL

### ISSUE THREAD

**Issue by SM-NSM** [longjunyu2/winlator#151]
**Device Information**
- Device Model: [e.g., Vivo IQOO Z9 Turbo]
- Device Processor Model: [e.g., Snapdragon 8s Gen 3]
- Android Version: [e.g., 14]
- Kernel Version: [e.g., 6.1.57-android14-11-maybe-dirty]

**Application Configuration Information**
- App Version: [e.g., 7.1.3 with native glibc]
- Display Driver: [e.g., Turnip-24.1.0]
- dxwrapper: [e.g., DXVK-2.3.1]
- box64 Version: [e.g., 0.3.0]
- box64 Preset: [e.g., Compatibility]

**Description of the Issue**
Winlator 7.1.3 with Native Glibc version's direct3d test doesn't start when I driver to turnip but works when I set it to VirGL .
But turnip works fine on winlator frost Proot.

**Steps to Reproduce**
Please describe the steps to reproduce the issue:
1. Download the native glibc winlator by longjunyu2 on iqoo z9 turbo 
2. Create contain and set driver to turnip and keep other setting default.
3. Start the container and try to start "test direct3d".

**Expected Behavior**
I expected to see the "test direct3d" work with any problems on turnip driver on my device.

**Screenshots**
![Screenshot_20241106_172104_com winlator](https://github.com/user-attachments/assets/761f202e-4d2b-4646-8690-b25f13f51233)

**Additional Information**
This problem only happens with the turnip driver but works fine with the VirGL driver. The screenshot that I have attached is with the VirGL driver on.
And my device works fine on winlator frost 7.1 V6  with turnip driver and VirGL driver with no problem.

**Comment by lvonasek** [comment]
Set TU_DEBUG env to noconform to fix the turnip compatibility issue in A6XX.

I will not use this fix because it causes lowered performance on other devices.
