### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by rhjdvsgsgks** [longjunyu2/winlator#152]
hi

would you consider publishing the app on F-Droid?

i also noticed there are some prebuilt libs exists. could you create a prebuilt script for them? so that it would match f-droid inclusion policy.

cc @linsui

**Comment by lvonasek** [comment]
I am sorry but we do not have capacity to do that. Several binaries are built by third party developers.

As this is a fork of the official Winlator. It is probably better to ask the original developer to find a way to F-Droid.
