### ISSUE TITLE
Request to add glibc (by Termux-Pacman) to your all "third-party apps" lists

### ISSUE THREAD

**Issue by Maxython** [longjunyu2/winlator#157]
Hello @lvonasek and @longjunyu2.
My name is Max Ivan and I am the maintainer of the [termux-pacman/glibc-packages](https://github.com/termux-pacman/glibc-packages) repository. I wrote this message to make a request to add a note about glibc (by @termux-pacman) to all your "third-party apps" lists (i.e. in your repository's README.md and in your winlator application). The reason for this request is the requirement to comply with [the MIT license of the termux-pacman/glibc-packages repository](https://github.com/termux-pacman/glibc-packages/blob/main/LICENSE.md), since you noted in the release (of your repository) that you used some sources (patches) from the [termux-pacman/glibc-packages](https://github.com/termux-pacman/glibc-packages) repository.
I hope for further cooperation, and maybe also on the glibc for winlator issue ;)

**Comment by lvonasek** [comment]
Hi Max, we are currently both on other projects but I added it into the next version milestone to not forget it before releasing an update.

Feel free to create a PR if you want to resolve it ASAP.
