### ISSUE TITLE
[Building] Build successful but imagefs will be invalid

### ISSUE THREAD

**Issue by SSUPII** [longjunyu2/winlator#160]
**Device Information**
*Building environment*
- Device Model: Macbook Air 2020
- Device Processor Model: Apple M1
- OS Version: Sonoma 14.1.2
- IDE: Android Studio Ladybug | 2024.2.1 Patch 2

*Target device*
- Device Model: Samsung Galaxy Tab S9+
- Device Processor Model: Qualcomm Snapdragon 8 Gen 2
- Android Version: 14
- Kernel Version: 5.15.123

**Application Configuration Information**
- App Version: Commit 8a1f1afd2cb55c78a7a5e526a0b5c6827dbc1d20

**Description of the Issue**
Cloning the repository into the IDE and building will make a succesfull build and install to the target device, but extraction of system files will immediately fail. The build created will have invalid/empty system images.

**Steps to Reproduce**
1. Clone repository into Android Studio
2. Click "Make Project"

**Expected Behavior**
Building should create proper archives, and no other action needed as mentioned by #70

**Screenshots**
![Screenshot_20241119_170933_Winlator](https://github.com/user-attachments/assets/04425674-6faf-466a-b4e6-92aa396f958f)
![Screenshot_20241119_171405_X-plore](https://github.com/user-attachments/assets/0369f0cc-d3fa-4519-8d5b-07aa775f112d)

**Additional Information**
The project was imported in Android Studio 2022.1.1 initially, but the IDE had to be updated to the current version due to the lack of support for the more recent Android Gradle Plugin version the project is using.

**Comment by lvonasek** [comment]
This happens when git-lfs is not installed. Install it and then call `git lfs pull` to pull the big files.
