### ISSUE TITLE
8GB Ram

### ISSUE THREAD

**Issue by TheBoxGame** [longjunyu2/winlator#163]
Hello add 8 GB Ram to Winlator please

**Comment by lvonasek** [comment]
There is only VRAM limitation (video memory size) and for that is 4GB sufficient.

If you have requests like this then please provide game/software name it requires such an amount.

**Comment by TheBoxGame** [comment]
@Ivonasek ok and what about the helix game that doesn't start because the game has a launcher that you can register and play the demo version when I run the icon twice nothing happens and the launcher should start

**Comment by lvonasek** [comment]
That's for sure not because of memory limitation.
