### ISSUE TITLE
Virtual key press feedback state Ui

### ISSUE THREAD

**Issue by 530l** [longjunyu2/winlator#166]
**Device Information**
- Device Model: [e.g., Samsung Galaxy S21]
- Device Processor Model: [e.g., Exynos 2100]
- Android Version: [e.g., 11]
- Kernel Version: [e.g., 4.19.112]

**Application Configuration Information**
- App Version: [e.g., 7.1.1]
- Display Driver: [e.g., Turnip-24.1.0]
- dxwrapper: [e.g., DXVK-2.3.1]
- box64 Version: [e.g., 0.3.0]
- box64 Preset: [e.g., Compatibility]

**Description of the Issue**
![image](https://github.com/user-attachments/assets/7e4dd9d8-ddac-4572-b085-f0e4ade4cdd9)
Hi, may I ask where the logic for the feedback ui effect under the press of these buttons is implemented, I didn't find it ？？？

**Comment by lvonasek** [comment]
It is here: https://github.com/longjunyu2/winlator/blob/f6188b30c3d48c0ff2895ef2d1effa99e8abe4ad/app/src/main/java/com/winlator/inputcontrols/ControlElement.java#L348

Based on `selected` it draws it with a slightly different color (depends on system theme).

I close this but feel free to ask more here.

**Comment by 530l** [comment]
No, maybe I'm not expressing myself clearly, it's the colour when you click and press? Is it also residing in selected. Distinguish between theme colours?

**Comment by lvonasek** [comment]
The size change is implemented here:
https://github.com/longjunyu2/winlator/blob/f6188b30c3d48c0ff2895ef2d1effa99e8abe4ad/app/src/main/java/com/winlator/widget/InputControlsView.java#L435

**Comment by 530l** [comment]
I pulled out the Ui layer, just the ControlElement, InputControlsView which are 2 controls related, no XService, so is it not possible to change the size? I went into Pointer.Button pointerButton = binding.getPointerButton();
                if (isActionDown) {
                    if (pointerButton ! = null) {
                        xServer.injectPointerButtonPress(pointerButton);
                    }
                    else xServer.injectKeyPress(binding.keycode);
                }
                else {
                    if (pointerButton ! = null) {
                        xServer.injectPointerButtonRelease(pointerButton); }
                    }
                    else xServer.injectKeyRelease(binding.keycode);
                } This logic.

**Comment by 530l** [comment]
` 
 Pointer.Button pointerButton = binding.getPointerButton();
                if (isActionDown) {
                    if (pointerButton != null) {
                        Log.d(ControlElement.tag, "injectPointerButtonPress pointerButton :" + pointerButton);
                    } else {
                        Log.d(ControlElement.tag, "injectKeyPress pointerButton :" + pointerButton);
                    }
                }

`
I pulled out these 2 controls to use on my end. When I look at the breakpoint, the pointerButton is null, but the XService is not used, so the effect of the virtual key press is not shown.

**Comment by lvonasek** [comment]
Interesting. I would expect the call comes from here:
https://github.com/longjunyu2/winlator/blob/f6188b30c3d48c0ff2895ef2d1effa99e8abe4ad/app/src/main/java/com/winlator/inputcontrols/ControlElement.java#L729

But hard to say this code was written by @brunosx

**Comment by 530l** [comment]
I actually just extracted those 2 controls (pure Ui without XService, TouchpadView, etc.), and when the demo was tested, I found that there was no click effect (press). I don't know where the click effect is set. Checked the source code for days and didn't see it.
