### ISSUE TITLE
[BUG]After adding a new drive letter to the drive options in winecfg, the path selection interface does not display the file path and cannot be selected

### ISSUE THREAD

**Issue by shishiwow** [longjunyu2/winlator#169]
**Device Information**
- Device Model: [e.g., Samsung Galaxy S23u]
- Device Processor Model: [e.g., 8gen2]
- Android Version: [e.g., 14]
- Kernel Version: [e.g., 4.19.112]

**Application Configuration Information**
- App Version: [e.g., 7.1.3]
- Display Driver: [e.g., Turnip-25.0.0]
- dxwrapper: [e.g., DXVK-2.5.2]
- box64 Version: [e.g., 0.3.2]
- box64 Preset: [e.g., Compatibility]

**Description of the Issue**
After adding a new drive letter to the drive options in winecfg, the path selection interface does not display the file path and cannot be selected
![fa00e93596876bdcf83f69a00cdf9cd](https://github.com/user-attachments/assets/784114c6-37be-43e6-9134-b242ceed8086)

**Comment by shishiwow** [comment]
![Uploading fa00e93596876bdcf83f69a00cdf9cd.jpg…]()

**Comment by shishiwow** [comment]
This issue affects some games that require mounting CDs to play, as it is not possible to install live games by mounting virtual CD drives

**Comment by lvonasek** [comment]
This is a limitation of Android 11+. Use the Winlator container settings to assign a path to drive. That should work fine.

**Comment by shishiwow** [comment]
I remember that in the past, the original version of Winlator was possible, and winecfg was very useful for mounting virtual optical drives, but glibc couldn't be used. I don't know if Winlator container settings for allocating drive paths can be set as optical drives in winecfg

**Comment by lvonasek** [comment]
WineCFG will not work because wine expect to have access to the whole system which on Android is a security issue.

Use the Winlator UI instead:
![Polish_20241225_102505293](https://github.com/user-attachments/assets/440947ab-419e-4301-835b-6595b0c45d7f)

**Comment by lvonasek** [comment]
We could try to implement the optical driver option into the Winlator UI if that helps.

**Comment by lvonasek** [comment]
I quickly checked it and you can add a drive using Winlator UI and then using WineCFG set it as an optical drive.

Hopefully that helps.

**Comment by shishiwow** [comment]
Okay, thank you very much!
