### ISSUE TITLE
[BUG] [BLACK] 

### ISSUE THREAD

**Issue by Dragonfire75** [longjunyu2/winlator#17]
![Screenshot_20240813-022344](https://github.com/user-attachments/assets/a7c3d326-d028-4ae3-a643-ceebd231bbd7)
![Screenshot_20240804-195622](https://github.com/user-attachments/assets/b3b1887a-6b73-4c43-8467-6d4ab29f110a)
![Screenshot_20240813-022826](https://github.com/user-attachments/assets/c79e3359-c3da-4001-9ec0-e141f50aa3af)
Idk why black?

**Comment by longjunyu2** [comment]
It's virgl issue maybe, still need more test...

**Comment by Dragonfire75** [comment]
![Screenshot_20240818-113857](https://github.com/user-attachments/assets/731a782c-fa2e-466a-a187-0b19a8e03c02)
![Screenshot_20240818-115507](https://github.com/user-attachments/assets/918db47a-a6cd-4f75-a1ce-24480f097f71)
![Screenshot_20240818-115331](https://github.com/user-attachments/assets/25a3d325-578b-44ce-b159-cbd5bd988c0a)
![Screenshot_20240818-115021](https://github.com/user-attachments/assets/0f5c4fb9-2605-4dcd-a17a-df824144818e)
![Screenshot_20240818-114949](https://github.com/user-attachments/assets/891ccdb8-9063-4b70-bd30-6ac1b41be858)
![Screenshot_20240818_115744](https://github.com/user-attachments/assets/aeedff9d-28fa-4ed7-aad1-cf1905dc86db)
![Screenshot_20240818-114844](https://github.com/user-attachments/assets/ff33d1a9-45ee-4123-a50c-b681fe6f7482)
![Screenshot_20240818-115605](https://github.com/user-attachments/assets/27ef2ab8-377e-4791-9193-547af0bf3ba1)
![Screenshot_20240818-114819](https://github.com/user-attachments/assets/8f8cab98-636f-4601-8700-31ecc9dba53d)
![Screenshot_20240818-115543](https://github.com/user-attachments/assets/4bfcb1d3-b9ea-410c-9efd-8e62ebdff3ca)
![Screenshot_20240818-115258](https://github.com/user-attachments/assets/644bd2f6-9cf3-476d-bf69-41876e418fff)
![Screenshot_20240818-115241](https://github.com/user-attachments/assets/7866abe6-49b4-4720-9b50-691aaccc1714)
![Screenshot_20240818-115115](https://github.com/user-attachments/assets/35cba78e-4673-4a0e-816f-cbfff47b8cf4)
![Screenshot_20240818-115109](https://github.com/user-attachments/assets/3c8880f9-da74-4420-abb0-5eedc90b204a)
![Screenshot_20240818-114119](https://github.com/user-attachments/assets/e51e5a5a-d716-4289-bbef-14a03ca4e4d1)
![Screenshot_20240818-114128](https://github.com/user-attachments/assets/54cd76a8-b3de-4c36-9557-08ea43446d39)
![Screenshot_20240818-114108](https://github.com/user-attachments/assets/4c2d6b06-a81a-42e4-95be-9014df120e90)
![Screenshot_20240818-114112](https://github.com/user-attachments/assets/ea733377-4bd0-4714-92f0-61a5091b9c60)
![Screenshot_20240818-114500](https://github.com/user-attachments/assets/eb22bc5a-72e4-42df-9d24-928852d5050d)
![Screenshot_20240818-115533](https://github.com/user-attachments/assets/2583e923-e6e9-4423-b560-47fd745aca23)
![Screenshot_20240818-114759](https://github.com/user-attachments/assets/abc58493-6f49-43bc-bd9f-ccbdd4a9b232)
![Screenshot_20240818-114251](https://github.com/user-attachments/assets/f0d83dcb-5f1e-4c51-8df9-c71f18d611f8)
![Screenshot_20240818-114316](https://github.com/user-attachments/assets/2bd9c239-0f31-47c5-a3e1-df24ef882734)

**Comment by Dragonfire75** [comment]
![Screenshot_20240818_133328](https://github.com/user-attachments/assets/6fab5e11-bfe8-40e2-95be-dd91a5ef7e54)
![Screenshot_20240818-114844](https://github.com/user-attachments/assets/9720b82e-26e1-4ccf-8cf6-1c46d64c06b1)

**Comment by nakele** [comment]
We might need an older version of virgl-mesa, 19.x or 18.x, this has solved the black on reflections for me on mali in termux. My understanding is that it requires less extension

**Comment by Dragonfire75** [comment]
winlator_glibc_7.1.4.apk test...
![Screenshot_20240820-042436](https://github.com/user-attachments/assets/d05e67a2-15c8-40aa-a94a-f31da39fb13c)
![Screenshot_20240820-042420](https://github.com/user-attachments/assets/2df534a6-ba82-4caf-9dc9-e0a804b4bd8f)

**Comment by longjunyu2** [comment]
I never publish a version called winlator glibc 7.1.4 until now.

**Comment by longjunyu2** [comment]
What is the game you are playing? I will have a look if at my free time..
