### ISSUE TITLE
Fit The Screen In XR Mode Not Working?

### ISSUE THREAD

**Issue by M4j0d1** [longjunyu2/winlator#175]
The Pre-Release 7.1.4 Says It Makes The XR Immersive Mode Fit The Screen Properly
However I Haven't Seemed To Notice a Difference From How It Was In 7.1.3

There Is Also a Black Square That Appears When You Start a Shortcut Now

**Comment by lvonasek** [comment]
It means the resolution of game and container do not have to match if you are in VR mode (not AR).

I just tested it and it works fine. The black square is expected.

**Comment by M4j0d1** [comment]
For Some Reason I Had To Re-Download 7.1.4 And Now It Works Somehow

Not Sure How That Happened
