### ISSUE TITLE
[QUESTION] Will using Bionic improve performance compared to Glibc?

### ISSUE THREAD

**Issue by RyanBram** [longjunyu2/winlator#177]
Hi, Developer.

Winlator Glibc is one of the applications I’m most excited about, as I believe this project represents a significant leap forward compared to similar initiatives.

I’m curious—would it be possible to further enhance the performance and compatibility of Windows applications by using the Bionic C library instead of Glibc? I came across a related discussion that might be of interest:

https://www.reddit.com/r/EmulationOnAndroid/comments/1h6edqo/micewine_an_windows_emulator_that_aims_to_use/

Thank you!

**Comment by lvonasek** [comment]
Yes but it will take some time until that is ready I'm this project.

I am closing this as a duplicate of #159
