### ISSUE TITLE
[SUGGESTION] New versioning scheme

### ISSUE THREAD

**Issue by RyanBram** [longjunyu2/winlator#178]
Hi, Developer,
As a fan of this project, I’d like to offer a suggestion.

In the README, I noticed that the versioning of future releases for Winlator Glibc seems to depend heavily on whether Bruno's latest upstream version of Winlator becomes open source or remains closed source (becoming 8 or remain 7).

I’d suggest basing Winlator Glibc’s versioning on major Wine releases instead of Bruno's Winlator. For example, when Wine version 10 is released, Winlator Glibc version number could change to10 as well. This would align with Wine’s improved Wayland support, which is also a focus of this project.

Additionally, perhaps a new name like Windroid could be considered, instead of Winlator Glibc.

Thank you

**Comment by lvonasek** [comment]
Hello, there are so many forks of Winlator and I do not want to start the chaos of different versioning.

So far WinlatorGlibc isn't much different from the Bruno's version, I do not consider renaming it to something else.
