### ISSUE TITLE
[BUG]GTA V memory leak?

### ISSUE THREAD

**Issue by MastaG** [longjunyu2/winlator#18]
**Device Information**
- Device Model: Samsung Galaxy S24 Ultra
- Device Processor Model: Snapdragon 8 Gen 3
- Android Version: 14
- Kernel Version: 6.1.25

**Application Configuration Information**
- App Version: 7.1.1-glibc
- Display Driver: Turnip 24.3.0 from Kimchi
- dxwrapper: DXVK-2.3.1 (also tried other versions)
- box64 Version: 0.3.0
- box64 Preset: performance

**Description of the issue**
I've copied the fitgirl repack release of GTA V to my phone's download folder.

It seems to run great for a while with the above settings.
But once I start driving around the city, during the first mission where you steal two cars.. eventually new assets will stop loading in.
This happens after a few minutes of driving.
The roads and buildings will show lowres versions of textures and after a while the game and winlator will freeze.

It's a shame because its working full speed at 720p.
I've tried to lower the resolution and settings, but it always seems to happen.

Any tips would be more then welcome :)

**Steps to Reproduce**
Please describe the steps to reproduce the issue:
1. Run GTA-V
2. Play the intro mission in the snowy town
3. Play the second mission where you steal a car and drive around the city

**Expected Behavior**
No memory leaks

**Screenshots**
If applicable, add screenshots to help explain your problem. You can attach screenshots here.

**Additional Information**
Please provide any other relevant information or context. For example, "This issue started happening after updating to version 1.2.3."

**Comment by longjunyu2** [comment]
emm...if you meat a memory leak, try `DXVK Config` -> set `Max Device Memory` to `512 MB`.

**Comment by MastaG** [comment]
I already fixed it.
I configured my phone to not try to limit memory and battery usage for winlator.
It's somewhere in the settings -> Device management.
Just add Winlator to the list of apps that shouldn't be memory limited and also for the "battery optimization".

Now it runs fine... already stole 2 cars.

I'm playing with a bluetooth controller.
Perhaps you can see if it's possible to implement rumble for the next release.
And bump box64 to the latest release :)
