### ISSUE TITLE
Support for Enhancement Files

### ISSUE THREAD

**Issue by CristobalManga** [longjunyu2/winlator#180]
Many PC games have mods to improve their performance or fix some problem with the game.

The problem is that most of the time these improvements come in a Xinput.dll file.

I'll give you the example of Resident Evil 5, to remove the filter and improve the camera there is a Xinput.dll file.

In the game Lost Planet 2, to fix the error that it closes unexpectedly, it is with a Xinput.dll file.

But even if I put the files in the game directory, it doesn't work.

And maybe it's my ignorance, but I think it's due to a conflict of the original Xinput.ll files that already come with Winlator that prevent it from invalidating the other Xinput files in the game. This doesn't happen with D3D9, since you can put a modified D3D9 and Winlator still recognizes it.

**Comment by lvonasek** [comment]
The DLL handling doesn't work the same way like on Windows. You need to go into Wine configuration and set XInput preferences to native to use your library:
![Screenshot_20241230_171332_com_winlator_XServerDisplayActivity](https://github.com/user-attachments/assets/07521407-6c77-4095-ba5f-62a17320b00d)

Hopefully this helps but note that it might cause some issues with the system input as the library is used to pass the touch input into the game.
