### ISSUE TITLE
[BUG] Not a BUG, 40fps options and resolutions.

### ISSUE THREAD

**Issue by Xintsuai** [longjunyu2/winlator#181]
Sorry about create this new item, would you add:

40fps support

Resolutions:

1300x600
1386x640
1560x720
2350x1080

Thanks for the awesone work.

**Comment by lvonasek** [comment]
These features are already there. If you select custom resolution then you can type any resolution you want:
![Screenshot_20241230_193511_com_winlator_MainActivity](https://github.com/user-attachments/assets/b0ed57e3-fdae-4486-a0b2-75f9a21458b9)

In DXVK setting you can set what FPS you want. There is 30 and 45FPS. But note that some games do not support it (they would be slowed down):
![Screenshot_20241230_193530_com_winlator_MainActivity](https://github.com/user-attachments/assets/9d0f513a-b6c4-471a-b3c6-a29953c405c1)
