### ISSUE TITLE
Turnip drivers

### ISSUE THREAD

**Issue by Sparda991** [longjunyu2/winlator#19]
Hi. Not a bug or anything, but wanted to see if you are able to include older turnip drivers, because a6xx for an example cant start Monster Hunter World without a crash on newer turnips, but on 24.0.0 it starts with no errors

**Comment by longjunyu2** [comment]
Hello, I have added turnip-23.3.0 as add-on for 7.1.2.

**Comment by longjunyu2** [comment]
Have you tried Turnip 23.3.0? If you still have questions, feel free to reopen the issue.
