### ISSUE TITLE
[BUG] Problem of not running most games on Snapdragon 870

### ISSUE THREAD

**Issue by Dragon-11976** [longjunyu2/winlator#22]
![Screenshot_2024-08-15-19-48-24-701_com kiwibrowser browser-edit](https://github.com/user-attachments/assets/4bfc25e8-03d7-4aa2-8905-ca4c98a8b542)
Hello 
afei glibc version, a fix has been added for my 870 processor. This fix runs most games without problems.
Can this problem be fixed in the next update? Thank you for everything 🫡

**Comment by MastaG** [comment]
So basically box64 from master git contains fixes for the snapdragon 870?

I'd also like nightly builds of box64.
It's constantly being updated with optimizations and bugfixes.

**Comment by longjunyu2** [comment]
@Dragon-11976 Box64 in 7.1.1 is not compiled with BAD_SIGNAL enabled. This will cause problems on any android device (especially on old kernel).

**Comment by Dragon-11976** [comment]
Ok thank you brother I understand the situation have a nice evening 😁

**Comment by longjunyu2** [comment]
Box64 in 7.1.2 was compiled with BAD_SIGNAL enabled. If you have any question, feel free to reopen this issue.
