### ISSUE TITLE
Bionic libc version?

### ISSUE THREAD

**Issue by Calidum** [longjunyu2/winlator#23]
There is reference to Wine on Termux works with Bionic libc.
https://github.com/alexvorxx/hangover-termux/releases

**Comment by longjunyu2** [comment]
Hello Calidum! bionic lib version is also a good way to run wine on Android. KreitinnSoftware is working on it. See https://github.com/KreitinnSoftware/MiceWine-Application

**Comment by longjunyu2** [comment]
If you have any further questions, feel free to reopen the issue.
