### ISSUE TITLE
Easier way to install addons/turnip.

### ISSUE THREAD

**Issue by Insertanamee** [longjunyu2/winlator#25]
The recent update has allowed custom content installation much easier, however it has also made setup a little more annoying as the latest box64 and turnip is not pre installed. 

I wanted to ask if you plan to create a website  that kind of acts like a store, or will it be built into the app like Horizon Emu, or if you have some other plans.

Also is it possible to make the custom winlator turnip into a .wcp file?

**Comment by longjunyu2** [comment]
Hello, Insertanamee! The introduction of the Additional Content Manager indeed lays the groundwork for online downloading of content packs.
  
Currently, there are no related plans, as a period of code refactoring is needed beforehand to make the project more maintainable and to address potential memory leak issues. Once the related work is completed, the functionality to fetch additional content online will be added to Winlator.
  
Creating wcp files is feasible.  On Linux, you can use tar xvf xxx.wcp to extract a wcp file, and on Windows, you can use 7-Zip. After extracting, the profile.json file inside contains the description information of the wcp.When packaging, please first create a tar archive of the root directory containing `profile.json`, and then compress it using xz or zstd to obtain a smaller wcp file.
  
I hope to improve the documentation support, but I’m currently busy with other work.

**Comment by lvonasek** [comment]
It is still needed to fill it with content but this is how it will work in the next update:

https://github.com/user-attachments/assets/09595b1b-ab6a-4bd2-9162-96c51e3d5ea2
