### ISSUE TITLE
[BUG] o resident evil 5 gold edition tá com tela preta no modo campanha

### ISSUE THREAD

**Issue by Joaopedro223** [longjunyu2/winlator#26]
**Device Information**
- Device Model: [e.g., Huawei p30 pro ]
- Device Processor Model: [e.g., KIRIN 980]
- Android Version: [e.g., 10]
- Kernel Version: [e.g., 4.12.112]

**Application Configuration Information**
- App Version: [e.g., 7.1.1]
- Display Driver: [e.g., Turnip-24.1.0]
- dxwrapper: [e.g., DXVK-2.3.1]
- box64 Version: [e.g., 0.3.0]
- box64 Preset: [e.g., Compatibility]

**Description of the Issue**
Please provide a clear and concise description of the problem. For example, "The app crashes when I try to open the settings menu."

**Steps to Reproduce**
Please describe the steps to reproduce the issue:
1. step 1
2. step 2
3. step 3

**Expected Behavior**
Please describe what you expected to happen. For example, "I expected to see the advanced settings without the app crashing."

**Screenshots**
If applicable, add screenshots to help explain your problem. You can attach screenshots here.

**Additional Information**
Please provide any other relevant information or context. For example, "This issue started happening after updating to version 1.2.3."

**Comment by longjunyu2** [comment]
Hello, Joaopedro223! I can't understand your message, please use English.

**Comment by Joaopedro223** [comment]
I can't play resident evil 5 it's black screen in campaign mode the character doesn't show up in the mali
