### ISSUE TITLE
[BUG] Wine 8.0.2 does not install

### ISSUE THREAD

**Issue by deivison01** [longjunyu2/winlator#27]
**Device Information**
- Device Model: [Redmi Note 12 Turbo]
- Device Processor Model: [Snapdragon 7+ Gen2]
- Android Version: [14]

**Application Configuration Information**
- App Version: [7.1.2]
- Display Driver: [Turnip-24.1.0]
- dxwrapper: [DXVK-2.3.1]
- box64 Version: [0.3.0]
- box64 Preset: [Compatibility]

**Description of the Issue**
When trying to install Wine 8.0.2, it gives the following error: "Profile not found in content".

**Steps to Reproduce**
Please describe the steps to reproduce the issue:
1. I downloaded Wine 8.0.2 referring to this one: https://github.com/brunodev85/wine-8.0.2-custom/releases/tag/8.0.2
2. I went to install Wine in the "Contents" tab of the emulator.
3. And it made an error: "Profile not found in content".

**Expected Behavior**
I expected the behavior to be similar to the "Wine-9.2-custom.wcp" file that was made available in the update and I couldn't find the "Wine-8.0.2-custom.wcp" version anywhere, I only found the "Wine- 8.0.2-custom.tar.xz".

**Screenshots**
![wine](https://github.com/user-attachments/assets/67c7f581-407f-4557-bc5d-c85338cdd2ca)

**Additional Information**
Nothing

**Comment by longjunyu2** [comment]
Hello, deivison01! The Wine used by Winlator with glibc requires additional custom modifications to work properly. Therefore, you cannot directly use the official Winlator version of Wine. This is also why I use the "wcp" suffix to identify additional files, making them distinguishable.
The good news is that I am currently trying to modify Wine 8.0.2 to work on Winlator with glibc, but this might take some time.

**Comment by longjunyu2** [comment]
support of wow64 on 8.0.2 is bad... Run anything on its wow64 mode is impossible. Sorry but this won't be fixed.
