### ISSUE TITLE
Dxvk.conf no work my brother 🥹🥹🥹

### ISSUE THREAD

**Issue by Azedin1111** [longjunyu2/winlator#3]

**Comment by longjunyu2** [comment]
This issue arises because Winlator generates a new `dxvk.conf` file each time it starts. Currently, please use environment variables instead of the configuration file. Improvements will be made in future updates :)

**Comment by longjunyu2** [comment]
[9450422](https://github.com/longjunyu2/winlator/commit/9450422aab87f0cd311a027bf86055fda47511c0)
This commit may fixed dxvk.conf support. And the default dxvk path is `/data/data/com.winlator/files/imagefs/home/xuser/.config/dxvk.conf` or use 'DXVK_CONFIG_FILE' to reset it.

**Comment by longjunyu2** [comment]
if it doesn't work, please reopen this issue.
