### ISSUE TITLE
MIDI Support 

### ISSUE THREAD

**Issue by TheBoxGame** [longjunyu2/winlator#32]
Hello add support MIDI and more in games Default Windows MIDI

**Comment by longjunyu2** [comment]
I have no idea about how to make midi work.. since it need alsa seq as kernel module.

**Comment by TheBoxGame** [comment]
> Nie mam pojęcia, jak sprawić, żeby działało midi, ponieważ wymaga to modułu jądra alsa seq.

and will the alsa seq module be added to MIDI playback because games like dx ball don't play music in the title screen and this game plays midi

**Comment by TheBoxGame** [comment]
> > Nie mam pojęcia, jak to możliwe, aby działać midi, ponieważ wymaga modułu jądra alsa seq.
> 
> i czy moduł ALSA SEQ zostanie dodany do Winlatora ponieważ gry takie jak DX Ball nie odtwarzają muzyki na ekranie tytułowym, a ta gra odtwarza MIDI i standardowy midi w windowsie tutaj jest standardowa muzyka z Microsoft GS Wavetable Synth
https://youtu.be/ReE2kEZsyWs?si=O0EatUAGstRaOXKl

**Comment by TheBoxGame** [comment]
@longjunyu2 add this soundfront 
[Uploading Microsoft GS Wavetable Synth.zip…]()

**Comment by longjunyu2** [comment]
> @longjunyu2 add this soundfront Uploading Microsoft GS Wavetable Synth.zip…

No, I won't add any soundfont that has no license to winlator. You should installed them by yourself.

**Comment by TheBoxGame** [comment]
@longjunyu2 this is the original soundfont from microsoft that windows uses by default

**Comment by longjunyu2** [comment]
@TheBoxGame Yes I know that, that's why I won't. It is non-free software, again You should installed them by yourself.

**Comment by TheBoxGame** [comment]
@longjunyu2 and how

**Comment by longjunyu2** [comment]
> @longjunyu2 Will there be an update tomorrow or the day after to download the application?

**PLEASE STOP** asking stupid question!!!

**Comment by TheBoxGame** [comment]
@longjunyu2 ok I understand

**Comment by longjunyu2** [comment]
you emailed me and both github issue, stop please

**Comment by TheBoxGame** [comment]
> wysłałeś mi maila i oba problemy z githubem, proszę przestań
good
