### ISSUE TITLE
[BUG]Steam update not downloading 

### ISSUE THREAD

**Issue by Riju2007123** [longjunyu2/winlator#34]
![Screenshot_2024-08-19-15-56-54-467_com android chrome](https://github.com/user-attachments/assets/fd36ce32-ec37-48a5-aa5b-579b72d687dd)
hey, I'm having problem with steam update download, the screen is like this for 10 mins and it's not downloading..

**Comment by longjunyu2** [comment]
Try killing `services.exe` in taskmgr. And Steam cannot work on the current Winlator... I am unable to solve any issues related to Steam.

**Comment by Riju2007123** [comment]
let's try it...
