### ISSUE TITLE
How to make wine file format .wcp

### ISSUE THREAD

**Issue by BravoSixGoing-Dark** [longjunyu2/winlator#35]
I just tried to make wine 9.14 into .wcp format file but I'm still confused how to get prefixPack.txz file for Wine 9.14 I hope you can answer it

**Comment by longjunyu2** [comment]
`prefixPack.txz' (other file name is allowed) contains a wine prefix which will to be extract to `imagefs/home/xuser/.wine`.
  
To build a prefixPack, you need to create a user named `xuser` and exec `WINEPREFIX=/path/to/prefix wine winecfg`. Then you will get wineprefix at /path/to/prefix. And then you can do any modifiy to it. After that, rename prefix folder to `.wine`, exec `tar cvf prefixPack.tar .wine` to pack and exex `xz -9 prefixPack.tar.xz` to compress.

**Comment by BravoSixGoing-Dark** [comment]
> `prefixPack.txz` (other file name is allowed) contains a wine prefix which will to be extract to `imagefs/home/xuser/.wine`.
> 
> To build a prefixPack, you need to create a user named `xuser` and exec `WINEPREFIX=/path/to/prefix wine winecfg`. Then you will get wineprefix at /path/to/prefix. And then you can do any modifiy to it. After that, rename prefix folder to `.wine`, exec `tar cvf prefixPack.tar .wine` to pack and exec `xz -9 prefixPack.tar.xz` to compress.

Okay thanks you so much👍

**Comment by sandstranger** [comment]
Wich wine dependencies should I install for building custom wine?

**Comment by 17857697984** [comment]
Sorry, I want to know the complete compilation process. I hope there is a big shot who can teach me
