### ISSUE TITLE
[BUG] System language

### ISSUE THREAD

**Issue by lvonasek** [longjunyu2/winlator#37]
**Application Configuration Information**
- App Version: 7.1.2

**Description of the Issue**
All the apps with a chinese localisation are in chinese although my device is set to english,

**Steps to Reproduce**
1. Go to device system settings
2. Set system language to english
3. Start Winlator
4. See start menu and apps (e.g. Winecfg) in chinese

**Expected Behavior**
When the system language is english then also Winlator should be in english.

**Additional Information**
This issue started happening after updating to version 7.1.2

**Comment by Dresserk** [comment]
> **Application Configuration Information**
> 
> * App Version: 7.1.2
> 
> **Description of the Issue** All the apps with a chinese localisation are in chinese although my device is set to english,
> 
> **Steps to Reproduce**
> 
> 1. Go to device system settings
> 2. Set system language to english
> 3. Start Winlator
> 4. See start menu and apps (e.g. Winecfg) in chinese
> 
> **Expected Behavior** When the system language is english then also Winlator should be in english.
> 
> **Additional Information** This issue started happening after updating to version 7.1.2

Where your list of containers are shown click on the 3-dot menu for the container and click EDIT. Midway down you'll see headers for options "Wine Configuration", "win Components", "Environment Variables", etc. Click "Environment Variables", scroll to the bottom and click ADD button, put "LC_ALL" for name and "en_US.utf8" for value, click OK. Be sure to use the same capitalization and underscores as shown.

**Comment by longjunyu2** [comment]
A temporarily solution is to set environment variables. I will add automatic regional language adjustment in future updates.
