### ISSUE TITLE
Dotnet Internal Error

### ISSUE THREAD

**Issue by TGP17** [longjunyu2/winlator#4]
I can't launch Stardew Valley with Winlator Glibc. It can launch with normal Winlator and Mobox. 

This is the error in the log:
021c:err:eventlog:ReportEventW L"Description: The process was terminated due to an internal error in the .NET Runtime at IP 000000027E8A7575 (000000027E890000) with exit code 80131506.\n"

I have also tried to install Wine Mono (which I didn't need to install on normal Winlator or mobox), which didn't change anything and had the exact same error message.

Let me know if I need to provide more info.

**Comment by longjunyu2** [comment]
soc, android version and kernel version please.

**Comment by TGP17** [comment]
SoC: Snapdragon 7+ Gen 2
Android version: 14
Kernel version: 5.10.198

**Comment by TGP17** [comment]
I just tried Stardew Valley on this: https://github.com/afeimod/winlator-mod/releases/tag/7.1.1-glibc-AmodFix
And it worked directly with VirGL. I removed all different environmental variables to rule out any changes from that and it still worked. 

I assume the ImageFS is different and added things that fixed the internal dotnet error. Is there maybe something missing or broken in your ImageFS?

**Comment by Saikatsaha1996** [comment]
> I can't launch Stardew Valley with Winlator Glibc. It can launch with normal Winlator and Mobox.
> 
> This is the error in the log: 021c:err:eventlog:ReportEventW L"Description: The process was terminated due to an internal error in the .NET Runtime at IP 000000027E8A7575 (000000027E890000) with exit code 80131506.\n"
> 
> I have also tried to install Wine Mono (which I didn't need to install on normal Winlator or mobox), which didn't change anything and had the exact same error message.
> 
> Let me know if I need to provide more info.

@longjunyu2 i also have same issue with wine 9.13.. and working fine with others wine.. so this is not winlator or box issues.. it's actually wine bug.. 

So please add support for custom wine or add more wine like 9.4, 9.5 etc

**Comment by longjunyu2** [comment]
@TGP17 @Saikatsaha1996 hello, I think this is a box64 issues which fixed on v7.1.2. And there is wine-9.2-custom provided if you like.

**Comment by Saikatsaha1996** [comment]
> @TGP17 @Saikatsaha1996 hello, I think this is a box64 issues which fixed on v7.1.2. And there is wine-9.2-custom provided if you like.

Will test & give you update

**Comment by TGP17** [comment]
Alright, the error is gone now and the game works. Thanks for fixing this 👍
