### ISSUE TITLE
[BUG] Failed to install Unreal Engine 4

### ISSUE THREAD

**Issue by 15815384899** [longjunyu2/winlator#48]
Why do some games require me to install Unreal Engine 4? How can I solve this problem?

**Comment by longjunyu2** [comment]
This is a game issue i think...
If you still have ant question, feel free to reopen this issue.

**Comment by longjunyu2** [comment]
> 兄弟是好几个游戏都是这样特别是国产恐怖游戏一打开就提示要我升级ue4虚幻引擎而且只升级了一半就卡住了
抱歉，我不知道怎么修复。你可以重启这个问题，也许别人有办法。

**Comment by 15815384899** [comment]
好我试试

**Comment by longjunyu2** [comment]
如果安装仍然遇到问题，请尝试在`编辑容器`->`环境变量`中关闭WINEESYNC，安装成功过后再打开。

**Comment by 15815384899** [comment]
解决了兄弟去下载安装了你说的2015插件就行了

**Comment by 15815384899** [comment]
不是wine更新9.16了吗多久可以适配呢

**Comment by longjunyu2** [comment]
> 不是wine更新9.16了吗多久可以适配呢
7.1.3默认wine-9.16
