### ISSUE TITLE
Add an option to disable the gamepad in individual games.

### ISSUE THREAD

**Issue by CristobalManga** [longjunyu2/winlator#49]
In most shooters or RTS games, it is better to control the camera with the touch.

Therefore I set the keyboard keys on my gamepad and control the camera with the touch.

But many games when they detect that there is a gamepad connected, they disable the touch. That is why I would be fine with disabling the gamepad.

**Comment by longjunyu2** [comment]
Thank you for your feedback. This issue seems to be fixed since #44. Next update will contain these changes.
