### ISSUE TITLE
Wine 9.2

### ISSUE THREAD

**Issue by Weizhy** [longjunyu2/winlator#5]
Can you make a version using Wine 9.2? Almost all my games don't work with 9.13. Tomb Raider Legend crashes at the loading screen, NFS Carbon crashes when I press start, and the same thing happens with NFS Underground 2. Only one game I tried didn't crash.

**Comment by iamzuika** [comment]
Need for speed Most Wanted (2005) dont work on wine 9.13 same.

**Comment by longjunyu2** [comment]
@Weizhy Please provide your SoC model, Android version, and kernel version.I have tested Tomb Raider Legend on 8gen2, with turnip and dxvk2.3.1.And the game ran well (60fps)

**Comment by Weizhy** [comment]
I'm using a Snapdragon 732G.
![Screenshot_2024-08-06-17-05-08-722_com android settings](https://github.com/user-attachments/assets/6d59ac31-bdb1-42be-b502-1794aa8de4c2)
And this is the error I get.
![Screenshot_2024-08-06-17-12-25-873_com winlator](https://github.com/user-attachments/assets/99c0d552-ae16-4be9-810b-0e18568e4ba7)

**Comment by Weizhy** [comment]
@longjunyu2 The latest afei mod fixed it somehow.

**Comment by longjunyu2** [comment]
> @longjunyu2 The latest afei mod fixed it somehow.

On older Android kernels,  it needs to compile box64 with BAD_SIGNAL=ON. I don't noticed it before last update.

**Comment by Saikatsaha1996** [comment]
> Need for speed Most Wanted (2005) dont work on wine 9.13 same.

Yes 9.13 wine had issue..
I tested best version 9.0 & 9.5 wine
