### ISSUE TITLE
[Bug] can't see changes/created input control in a container until reset

### ISSUE THREAD

**Issue by Armagedon13** [longjunyu2/winlator#55]
**Device Information**
- Device Model: Motorola Edge 30 Pro
- Device Processor Model: Qualcomm Snapdragon 8 Gen 1
- Android Version: 13
- Kernel Version: 5.10.198

**Application Configuration Information**
- App Version: 7.1.2
- Display Driver: Turnip-24.3.0
- dxwrapper: DXVK-1.10.3-1
- box64 Version: 0.3.0
- box64 Preset: Compatibility

**Description of the Issue**
When you change/create a input control while you are in a container you need to close the actual container to see the changes.

**Steps to Reproduce**
Please describe the steps to reproduce the issue:
1. open a container
2. change the input control or create a new one
3. you can't select the new saved controls

**Expected Behavior**
see the saved changes and apply in the actual container

**Comment by longjunyu2** [comment]
Thank you for your feedback, I will work on this.
