### ISSUE TITLE
[BUG] Black screen on Meta QuestOS v69

### ISSUE THREAD

**Issue by lvonasek** [longjunyu2/winlator#57]
**Device Information**
- Device Model: Meta Quest 2/3/Pro
- Android Version: 12 (v69)

There is a black screen on Meta QuestOS v69 caused by OS change in the depth butfer.

I will fix that in the next 24 hours. @longjunyu2, would you mind holding the release until I fix that?

**Comment by longjunyu2** [comment]
@lvonasek Okay, I won't rush to release the next release. I also have a few feedbacks that need to be addressed.
