### ISSUE TITLE
Age of Empires 2 DE dump error

### ISSUE THREAD

**Issue by Sparda991** [longjunyu2/winlator#6]
This game runs fine on official Winlator, but here I have this error. Although discord user akagloomy runs it fine. His phone is 8gen2 and mine is 870 with android 11. Does glibc has some issues with my phone or somehing with glibc needs to be done? 
![Screenshot_2024-08-06-01-22-38-661_com winlator](https://github.com/user-attachments/assets/81308ada-7cfa-4beb-9de0-adfd641568a5)

**Comment by Sparda991** [comment]
[logs.txt](https://github.com/user-attachments/files/16509336/logs.txt)

**Comment by longjunyu2** [comment]
Android version and kernel version please.

**Comment by Sparda991** [comment]
> Android version and kernel version please.

![Screenshot_2024-08-07-09-51-26-776_com android settings](https://github.com/user-attachments/assets/0c97534d-6fb6-4a4a-aaa9-0203918ca9de)

**Comment by Sparda991** [comment]
Is this error maybe related to not having access to C drive or maybe driver problem?

**Comment by longjunyu2** [comment]
@Sparda991 I don't have 870 device, so I can't test the game on my side :(
  Have you tested it on mobox? And how it worked if you did that.

**Comment by Sparda991** [comment]
> @Sparda991 I don't have 870 device, so I can't test the game on my side :( Have you tested it on mobox? And how does it work if you did that.

Game works fine in mobox, darkos, even winlator official and modded ones. Only here in this glibc mod doesnt work. You think it may be issue with sd870? Maybe drivers are issue, idk. Can you add a6xx drivers too in next update?

**Comment by Sparda991** [comment]
@longjunyu2 I believe mesa 23.9.9 or is it 24.0.0 works the best with a6xx. Idk how glibc works woth different kernels or android versions, does that have anything related to issue I have

**Comment by Sparda991** [comment]
@longjunyu2 sorry to bother you. Afei released modded version of your glibc and here game works fine also. I guess you may know what the fix is. I hope you fix it future update. Thanks for glibc mod too. 
![Screenshot_2024-08-08-23-59-04-355_com winlator](https://github.com/user-attachments/assets/71af8ab6-d067-43bd-b1ce-c9323570bb41)
