### ISSUE TITLE
prince of persia (2008) black screen problem 

### ISSUE THREAD

**Issue by ahmedtalha31** [longjunyu2/winlator#66]
I try run pop 2008 (dx9 game) on virgil driver as my gpu is Mali but when i run it i hear the sound of the game and give me black screen. Is that game virgil driver can't run it or there are something wrong with my settings??

**Comment by longjunyu2** [comment]
please provider the box64 vrsion you are using, and if you want to report a bug, you are supposed to [follow] this(https://github.com/longjunyu2/winlator/blob/main/.github/ISSUE_TEMPLATE/bug_report.en.md)

**Comment by ahmedtalha31** [comment]
> please provider the box64 vrsion you are using, and if you want to report a bug, you are supposed to [this](https://github.com/longjunyu2/winlator/blob/main/.github/ISSUE_TEMPLATE/bug_report.en.md)
My box64 version is 0.3.0 and i think it isn't bug may be the current virgil driver can't run the game as i don't try it on other phone with mali gpu so i am not sure

**Comment by lvonasek** [comment]
This is duplicate of #111. Closing this one as the other report contains more details.
