### ISSUE TITLE
Add nonwow64 support

### ISSUE THREAD

**Issue by BravoSixGoing-Dark** [longjunyu2/winlator#69]
I think It would be nice if there was nonwow64 support because wow64 has bad performance for old games like GTA Sa and others

**Comment by ABOD123456788** [comment]
No Mincrft

**Comment by longjunyu2** [comment]
Sorry I won't do that since 8gen3 and later won't support armv7. If wow64 do causes performance droping, then wait wine update.

**Comment by BravoSixGoing-Dark** [comment]
> Sorry I won't do that since 8gen3 and later won't support armv7. If wow64 do causes performance droping, then wait wine update.

Owh Okay thanks for answering
