### ISSUE TITLE
Not bug!  Different AppID?!

### ISSUE THREAD

**Issue by QrTa** [longjunyu2/winlator#7]
Is it possible to make a version which isn't wants to be installed as an update to the original Winlator? 

It would be pretty cool to have both to compare/test games. 

People could test it without dealing to reinstall everything every time if wants to change between the versions.

**Comment by longjunyu2** [comment]
Changed appid means to recompile the whole project (not only app, but imagefs). It is because many hard coded paths are used in imagefs, such as /data/data/com.winlator/files/inagefs/usr/share. So i recommanded to compile the offical winlator with different appid. It will be easier because proot don't need hard coded path.

**Comment by QrTa** [comment]
@longjunyu2 Thank you for your time to answer and clear out these things for me.
Then maybe I try to do that.
Just remember what appid I used to update Winlator every time.

**Comment by longjunyu2** [comment]
> @longjunyu2 Thank you for your time to answer and clear out these things for me. Then maybe I try to do that. Just remember what appid I used to update Winlator every time.

  Sorry that I made a mistake. I confused package name and appid (because some people asked me about modifying package name before).For appid, I will improve the app to handle updates correctly.

**Comment by longjunyu2** [comment]
> > @longjunyu2 Thank you for your time to answer and clear out these things for me. Then maybe I try to do that. Just remember what appid I used to update Winlator every time.
> 
> Sorry that I made a mistake. I confused package name and appid (because some people asked me about modifying package name before).For appid, I will improve the app to handle updates correctly. But I think it's impossible to inatall winlator-glibc when winlator-offical installed already, beacuse they have different apk signature.

**Comment by QrTa** [comment]
I mean if I modify vanilla Winlator appID to install glibc separately I need to modify that Vanilla Winlator appID every time I want to update it.

**Comment by ashraf456** [comment]
> > I mean if I modify vanilla Winlator appID to install glibc separately I need to modify that Vanilla Winlator appID every time I want to update it.
> 
> Yes, that's right..


Hii , how did you build glibc imagefs ? My friend is working on glibc based emulator apk . But problem is glibc packages.
Is that any another method to build glibc packages. 
Or you used to Termux-pacman repo ?
Please answer me it's really important.

**Comment by longjunyu2** [comment]
@ashraf456 Termux-pacman's glibc is good enough to run box64 and wine. I used some patches from that project.

**Comment by ashraf456** [comment]
> @ashraf456 Termux-pacman's glibc is good enough to run box64 and wine. I used some patches from that project.


How did you manage to build glibc and other packages with custom package name ?

Did you use cgct method or Ubuntu method?

**Comment by longjunyu2** [comment]
> > @ashraf456 Termux-pacman's glibc is good enough to run box64 and wine. I used some patches from that project.
> 
> How did you manage to build glibc and other packages with custom package name ?
> 
> Did you use cgct method or Ubuntu method?

If you like, you can use 'sed' to change package name in .patch to your own's app.
Sorry but I don't know what is cgct...

**Comment by longjunyu2** [comment]
@ashraf456 how about open a new issues?
