### ISSUE TITLE
compiling instructions

### ISSUE THREAD

**Issue by wa0101** [longjunyu2/winlator#70]
It would be very good if you add the complete method to build/compile winlator on android studio in readme
Anyway, thank you for the great work

**Comment by longjunyu2** [comment]
just clone and build.

**Comment by longjunyu2** [comment]
Did it compile successfully?

**Comment by wa0101** [comment]
Oh, I thought that like the original repo it has a lot of problems,  i will try now C:

**Comment by wa0101** [comment]
**Everything works perfectly! Thank you for everything** ♥♥

**Comment by longjunyu2** [comment]
Cheers! I will improve the doc in the future.
