### ISSUE TITLE
[BUG] poor perfomance on winlator glibc 7.1.3 on A725

### ISSUE THREAD

**Issue by brujo5** [longjunyu2/winlator#71]
**Device Information**
- Device Model: poco f5
- Device Processor Model: 7+gen2
- Android Version: 14
- Kernel Version: 5.10.218

**Application Configuration Information**
- App Version: 7.1.3
- Display Driver: Turnip-24.3.0
- dxwrapper: DXVK-2.4,2.3.1,etc
- box64 Version: 0.3.1
- box64 Preset: any preset

**Description of the Issue**
First of all, wine 9.16 is terrible in performance, confirmed by other devs like darkos, you should leave wine 9.15 as default and any other new version as optional.
Yesterday I installed the new version from scratch and I have noticed that the fps are unstable compared to the previous version using the same settings, drivers, prest etc. as an example in the game stray in the previous version it goes to 35-45fps 1280x720 and in the new version 25-29 fps and very unstable.
Old gamepad support was removed and some games still require it, xinput, dinput and also axis or button are useless as they do not fix it

**Comment by brujo5** [comment]
Wine 9.2 is not good either, as there are games that have bugs with the controls, such as Resident Evil, and that was fixed in Wine 9.14, 9.15.

for me wine 9.15 best

**Comment by brujo5** [comment]
OK, i try

**Comment by brujo5** [comment]
That was the first thing I did but it didn't work, I tried the same drivers I used in the previous version in the new one but the performance is not good, a725/730 is very sensitive to any change in the turnip debug settings and if there was any change there, that is possibly the cause.

**Comment by K11MCH1** [comment]
> That was the first thing I did but it didn't work, I tried the same drivers I used in the previous version in the new one but the performance is not good, a725/730 is very sensitive to any change in the turnip debug settings and if there was any change there, that is possibly the cause.

Turnip support for the a725 and a730 are early. It is expected.
I have talked with some users of a730 and up and there was no performance regression observed.

**Comment by longjunyu2** [comment]
I think I need more informations about your situation. In fact I never removed old gamepad support, you are supposed to enable dinput in Advance tab.

**Comment by Luihart** [comment]
Just leave wine 9.13 - 9.16  optional installment. Wine 9.16 fixed performance in splinter cell blacklist. So we can use different wine for different games. Thank you for all the hard work!

**Comment by lvonasek** [comment]
Wine 9.15 will be in the content downloader in the next update. In the current version you can sideload it from here:
https://github.com/longjunyu2/winlator/releases/download/v7.1.3/wine-9.15-custom.wcp

Packaged by longjunyu2, thanks.
