### ISSUE TITLE
[BUG] box64rc import not working properly 

### ISSUE THREAD

**Issue by ajay9634** [longjunyu2/winlator#72]
**Device Information**
- Device Model: [Poco M2 pro]
- Device Processor Model: [snapdragon 720g]
- Android Version: [12]

**Application Configuration Information**
- App Version: [7.1.3]
- Display Driver: [e.g., Turnip-24.1.0]
- dxwrapper: [e.g., DXVK-2.3.1]
- box64 Version: [e.g., 0.3.0]
- box64 Preset: [e.g., Compatibility]

**Description of the Issue**

 The box64rc profile error is "unable to import profile"

**Steps to Reproduce**
Please describe the steps to reproduce the issue:
1. step 1 - create box64rc profile then export rcp
2. step 2 - trying to import but saying error 
3. step 3- the error is "unable to import profile"

**Expected Behavior**
It should be imported properly.

**Screenshots**

https://github.com/user-attachments/assets/51884627-6e19-4e01-968a-cd346fca3d4d

**Additional Information**
rcp profile is working when it is added directly to apk.

**Comment by longjunyu2** [comment]
Would you like to upload your rcp file?
