### ISSUE TITLE
DirectDraw Games 320x200 to Full Screen

### ISSUE THREAD

**Issue by TheBoxGame** [longjunyu2/winlator#76]
Would you add a DirectDraw option so that games that support this option after changing the resolution to 640x480 would work normally? I mean the game Neo Sonic Universe. The game is in a small window even after selecting the DirectDraw option in the game settings and the 320x200 resolution is a disaster. DirectDraw games support the 320x200 resolution despite increasing the resolution to 1920x1080. The game will start in 320x200 and if the game is turned off, the resolution will be as it is set.

Uploading Screenrecorder-2024-08-31-17-18-06-86.mp4…

**Comment by lvonasek** [comment]
Did you try the magnifier function? (back menu when the container is running, in the menu click "magnifier" and then hit plus button)

**Comment by TheBoxGame** [comment]
it doesn't help, I have to use the magnifying glass every time just to make the game full screen, it makes no sense

**Comment by lvonasek** [comment]
Could you reupload the video where you show the issue?

**Comment by TheBoxGame** [comment]
https://github.com/user-attachments/assets/db2d7c24-1cd7-4a00-947c-f0979710360c

**Comment by TheBoxGame** [comment]
> Czy możesz ponownie przesłać film, na którym pokazujesz ten problem?

Yes

**Comment by lvonasek** [comment]
The fix will be part of the next release.

**Comment by FriesBv** [comment]
I think adding this causes some other apps to be forced to use the "Force Fullscreen" option, I don't know if it's a mistake on my part or a bug after this addition.

https://github.com/user-attachments/assets/0c249738-16a3-4420-822d-6bae5636a159

**Comment by lvonasek** [comment]
It is a bug. It will be fixed in the 7.1.5 build.
