### ISSUE TITLE
Nothing Related to App

### ISSUE THREAD

**Issue by ashraf456** [longjunyu2/winlator#8]
Hii how to patch glibc using sed can you give me some commands ? Or any hint?

**Comment by longjunyu2** [comment]
This sctipt shows how to do that.
  [termux_step_patch_package](https://github.com/termux-pacman/termux-packages/blob/master/scripts/build/termux_step_patch_package.sh)

**Comment by ashraf456** [comment]
> This sctipt shows how to do that.
>   [termux_step_patch_package](https://github.com/termux-pacman/termux-packages/blob/master/scripts/build/termux_step_patch_package.sh)

Did you build on Termux ?

**Comment by ashraf456** [comment]
Hii ,
I already builded glibc . 
But now I am stuck at building glibc packages like mesa, libx11,

I want to build full glibc with required packages to run wine on it . 
For different apk.
If you want to help me .
Contact here :- 
Telegram :-  @gamextra4u

Discord :- gamextra4u

**Comment by longjunyu2** [comment]
@ashraf456 I'm sorry, I missed your reply and didn't see this email. QAQ please forgive me. 
And I don't have a Discord or Telegram account (it's difficult to register them for me). If you still have any issues, feel free to contact me through github or 877730493@qq.com.
