### ISSUE TITLE
Help: kron4ek wow64 wine support?

### ISSUE THREAD

**Issue by ajay9634** [longjunyu2/winlator#87]
@longjunyu2  Hi,

Can you tell me a guide about using kron4ek wow64 wine in winlator glibc ?

I want to use kron4ek wow64 wine but unfortunately it's not working.

Only wine configuration opened then container immediately crashed.

I am a Noob in compiling stuff.

**Comment by longjunyu2** [comment]
@ajay9634 kron4ek's wine cannot run directly since it needs some patches to work.

**Comment by longjunyu2** [comment]
@ajay9634 pc i think. I am maintaing a wine-custom, you can view commits to get what i have done...

**Comment by longjunyu2** [comment]
> Thanks,
> 
> Nice , You are adding contents download feature of wine and other stuff.
> 
> I have a question, old wine content keep old Xinput dinput or latest Xinput dinput?

latest xinput dinput
