### ISSUE TITLE
I can't run config.exe

### ISSUE THREAD

**Issue by TheBoxGame** [longjunyu2/winlator#88]
I can't run config.exe in Spacecraft
after double clicking on config.exe the configuration doesn't start

https://github.com/user-attachments/assets/320486a6-3f54-42a2-95c1-21318b882adc

**Comment by TheBoxGame** [comment]
@lvonasek hello how to fix

**Comment by lvonasek** [comment]
Please do not ping me. Enable logging, reproduce the issue and then post the log here, so we can log into it.

**Comment by TheBoxGame** [comment]
> Cytuj odpowiedź
> Odniesienie

ok and will this problem be solved in the next update

**Comment by lvonasek** [comment]
It isn't planned. The priories for the next update are: https://github.com/longjunyu2/winlator/milestone/1
