### ISSUE TITLE
Can't boot Devil May Cry 4 Original

### ISSUE THREAD

**Issue by BravoSixGoing-Dark** [longjunyu2/winlator#9]
Devil may cry 4 Original can run on official Winlator why can't I play this version

Phone: Oppo a96 
Chipset: Snapdragon 680
Android Version: 13
Kernel Version: 4.19.157

**Comment by BravoSixGoing-Dark** [comment]
Don't worry sir afei already released the version modded of your Winlator and now Devil May cry 4 can boot
![Uploading Screenshot_2024-08-08-21-39-44-76_b6022cb7d1a61f21e4fe914c8728a54c.jpg…]()

**Comment by longjunyu2** [comment]
v7.1.2 also fixed this
